name: Build weather
on: [workflow_dispatch, push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt install librsvg2-bin pngcrush python2
          which python
          python --version
      - run: echo "Test 2"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "üçè This job's status is ${{ job.status }}."
